"""empty message

Revision ID: 178eaae2510c
Revises: 
Create Date: 2018-12-04 16:06:24.488296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178eaae2510c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_register_time'), 'user', ['register_time'], unique=False)
    op.create_table('login_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_log_time'), 'login_log', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_log_time'), table_name='login_log')
    op.drop_table('login_log')
    op.drop_index(op.f('ix_user_register_time'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
