"""empty message

Revision ID: 47b7094b49bc
Revises: 51c57fbf6601
Create Date: 2018-12-11 19:50:02.905089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b7094b49bc'
down_revision = '51c57fbf6601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('create_time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'create_time')
    # ### end Alembic commands ###
