"""empty message

Revision ID: 51c57fbf6601
Revises: 87404378c239
Create Date: 2018-12-11 19:49:47.865002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c57fbf6601'
down_revision = '87404378c239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('create_time', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
